/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vehicles;

import vehicles.models.TransportHub;

public class App {
    public static void main(String[] args) {
        TransportHub transportHub = new TransportHub();

        // Car car1 = new Car("red", "Honda", 2004, 4, "gas");
        // transportHub.addVehicle(car1);

        // Ship ship1 = new Ship("blue", "Denmark", 1988, 42.42, 42);
        // transportHub.addVehicle(ship1);

        Vehicle vehicle = new Vehicle();

        
    }
}
